Fix migration.db_version when no tables
When db_version was called and the database wasn't controlled
it would call db_version_control without an engine which would
lead to an unexpected error being raised:

 TypeError: coercing to Unicode: need string or buffer, int found

This is because it was passing the version (an int) where the
argument is supposed to be the path.

Change-Id: Ie724c2c53ba9da3206a28a0e9d3725ed0f170579