wrap dict with list() in for loop
In python 3, if the dict is changed in the loop, there will be
following error:
RuntimeError: dictionary changed size during iteration

Tranfrom dict with list() to fix it.

Bug #1240725

Change-Id: I169b13546bcd0d87353dbca5a9b64229b704fe66