openstack.common.setup: fails to get version from git
quantum run_tests.py fails because
openstack.common.setup._get_version_from_git fails.  It is because
quantum unit tests run under quantum/tests/unit instead of git root dir.
So the function should check parent dirs for .git.

ERROR: test_network_gateway_update (quantum.tests.unit.nicira.test_networkgw.NetworkGatewayExtensionTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "quantum/quantum/tests/unit/nicira/test_networkgw.py", line 70, in setUp
    config.parse(args=args)
  File "quantum/quantum/common/config.py", line 99, in parse
    version='%%prog %s' % quantum_version.release_string())
  File "quantum/quantum/openstack/common/version.py", line 63, in release_string
    self.release = self._get_version_from_pkg_resources()
  File "quantum/quantum/openstack/common/version.py", line 56, in _get_version_from_pkg_resources
    return setup.get_version(self.package)
  File "quantum/quantum/openstack/common/setup.py", line 334, in get_version
    raise Exception("Versioning for this project requires either an sdist"
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository.

Change-Id: I2e24c00b5ba8f35381cac081ff72d86ea0d75d19
Fixes: bug #1131162
Signed-off-by: Isaku Yamahata <yamahata@valinux.co.jp>