python3: Fix UserString import
In python3 UserString got moved to collections. This results in the
following traceback while running with python3:

ImportError: No module named 'UserString'

Change-Id: Ica44cd027e012e13828c0a84b3b36607cc92fe69
Signed-off-by: Chuck Short <chuck.short@canonical.com>