save_and_reraise_exception: make logging respect the reraise parameter
Do not log original exception if reraise is set to False

Closes-Bug: #1291850
Related-Bug: #1288188

Change-Id: Icd5fcba25c2cd549cee70353a7a62d83bfe1255b