save_and_reraise_exception: add a flag to omit logging original exception
For some cases there is no need to log original exception

Change-Id: Icd5fcba25c2cd549cee70353a7a62d83bfe1255b
Closes-Bug: #1291850